version: '3'

services:
  backend:
    build:
      context: ./server
    container_name: finance-bot-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build:
      context: ./client
    container_name: finance-bot-frontend
    ports:
      - "3000:80"  # Port 3000 on host maps to 80 inside the container (served by nginx)
    depends_on:
      - backend
    restart: always